USE RestaurantManagement
GO
CREATE TABLE ThucDon(
	MaTD varchar(10) CONSTRAINT TD_MTD_PK PRIMARY KEY NOT NULL,
	NgayBatDau Date NOT NULL,
	NgayKetThuc Date NOT NULL
)
GO
CREATE TABLE DonVi(
	MaDV varchar(10) CONSTRAINT DV_MDV_PK PRIMARY KEY NOT NULL,
	TenDV nvarchar(20) CONSTRAINT DV_TDV_UNI UNIQUE NOT NULL,
)
GO
CREATE TABLE KhuyenMai(
	MaKM varchar(10) CONSTRAINT PK_KM PRIMARY KEY NOT NULL,
	TenKM nvarchar(50) CONSTRAINT UNI_KM UNIQUE NOT NULL,
	NgayBatDau Date NOT NULL,
	NgayKetThuc Date NOT NULL,
	GiamGia int NOT NULL
)
GO
CREATE TABLE Ban(
	MaBan varchar(10) CONSTRAINT PK_Ban PRIMARY KEY NOT NULL,
	TenBan nvarchar(50) NOT NULL,
	LoaiBan varchar(10) NOT NULL,
	TrangThai int NOT NULL
)
GO
CREATE TABLE NhanVien(
	MaNV varchar(10) NOT NULL,
	TenNV nvarchar(100) NOT NULL,
	MatKhau varchar(10) NOT NULL,
	NgaySinh date NOT NULL,
	ChucVu int NOT NULL,
	CONSTRAINT PK_NhanVien PRIMARY KEY(MaNV)
)
GO
CREATE TABLE MonAn(
	MaMA varchar(10) CONSTRAINT PK_MA PRIMARY KEY NOT NULL,
	TenMonAn nvarchar(100) CONSTRAINT UNI_MA UNIQUE NOT NULL,
	Nhom nvarchar(50) NOT NULL,
	Loai nvarchar(50) NULL,
	MaDV varchar(10) NOT NULL,
	GiaTien float NOT NULL,
	CONSTRAINT FK_MA_DV FOREIGN KEY(MaDV) REFERENCES DonVi(MaDV)
)
GO
CREATE TABLE HoaDon(
	MaHD varchar(10),
	MaNV varchar(10) NOT NULL,
	GioVao datetime NOT NULL,
	GioRa datetime,
	TongTien float,
	CONSTRAINT PK_HoaDon PRIMARY KEY(MaHD),
	CONSTRAINT FK_HD_NV FOREIGN KEY(MaNV) REFERENCES NhanVien(MaNV)
)
GO
CREATE TABLE ChiTietTD(
	MaTD varchar(10) NOT NULL,
	MaMA varchar(10) NOT NULL,
	CONSTRAINT PK_TDMA PRIMARY KEY(MaTD, MaMA),
	CONSTRAINT FK_TDMA_MA FOREIGN KEY(MaMA) REFERENCES MonAn(MaMA)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_TDMA_TD FOREIGN KEY(MaTD) REFERENCES ThucDon(MaTD)
	ON DELETE CASCADE ON UPDATE CASCADE
)
GO
CREATE TABLE ChiTietKM(
	MaKM varchar(10) NOT NULL,
	MaMA varchar(10) NOT NULL,
	CONSTRAINT PK_CTKM PRIMARY KEY(MaKm,MaMA),
	CONSTRAINT FK_CTKM_MA FOREIGN KEY(MaMA) REFERENCES MonAn(MaMA)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CTKM_KM FOREIGN KEY(MaKM) REFERENCES KhuyenMai(MaKM)
	ON DELETE CASCADE ON UPDATE CASCADE
)
GO
CREATE TABLE ChiTietHD(
	MaHD varchar(10) NOT NULL,
	MaMA varchar(10) NOT NULL,
	GiaTien float NOT NULL,
	SoLuong int NOT NULL,
	ThanhTien float,
	CONSTRAINT PK_CTHD PRIMARY KEY(MaHD,MaMA),
	CONSTRAINT FK_CTHD_MA FOREIGN KEY(MaMA) REFERENCES MonAn(MaMA)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CTHD_HD FOREIGN KEY(MaHD) REFERENCES HoaDon(MaHD)
	ON DELETE CASCADE ON UPDATE CASCADE
)
GO
CREATE TABLE BanHD(
	MaHD varchar(10) NOT NULL,
	MaBan varchar(10) NOT NULL,
	CONSTRAINT PK_BanHD PRIMARY KEY(MaHD, MaBan),
	CONSTRAINT FK_BanHD_Ban FOREIGN KEY(MaBan) REFERENCES Ban(MaBan),
	CONSTRAINT FK_BanHD_HD FOREIGN KEY(MaHD) REFERENCES HoaDon(MaHD)
	ON DELETE CASCADE ON UPDATE CASCADE
)
GO
CREATE TABLE DatBan(
	KhachHang nvarchar(100) NOT NULL,
	ThoiGian datetime NOT NULL,
	SoBan int NOT NULL,
	Ban varchar(50) NOT NULL
)